use Vendas


SELECT CLIENTE.nome, CIDADE.NOME, VENDAS.qtd 
FROM CLIENTE
INNER JOIN CIDADE ON CLIENTE.id_cidade=CIDADE.id
INNER JOIN VENDAS ON CLIENTE.ID=VENDAS.id_cliente
WHERE CIDADE.nome = 'Lisboa' 
