//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oficina.Model
{
    using System.Collections.Generic;

    public partial class Cliente
    {
        public Cliente()
        {
            this.FolhasObra = new HashSet<FolhaObra>();
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public string NIF { get; set; }

        public virtual ICollection<FolhaObra> FolhasObra { get; set; }
    }
}
