//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oficina.Model
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FolhaObra
    {
        public int Id { get; set; }
        public int ClienteId { get; set; }
        public DateTime DataEntrada { get; set; }
        public string Matricula { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public int? Km { get; set; }
        public string ProblemaDescrito { get; set; }
        public string ServicosRealizados { get; set; }
        public string Estado { get; set; }
        public decimal? ValorTotal { get; set; }

        public virtual Cliente Cliente { get; set; }

        [NotMapped]
        public string NomeCliente { get; set; }
    }
}
