//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oficina.Model
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class OficinaEntities : DbContext
    {
        public OficinaEntities()
            : base("name=OficinaEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<FolhaObra> FolhasObra { get; set; }
    }
}
